### ISSUE TITLE
没有办法解析select *

### ISSUE THREAD

**Issue by ma1231** [L11168032/sql-lineage-parser#1]
可以支持吗

**Comment by L11168032** [comment]
这是一个完全基于语法解析来获取血缘关系的轻量级工具（不涉及具体数据库操作），select * 从语法角度是无法获取到列信息的。
提供两种思路：

1. 建立规范，禁止select * 写法。从数据仓库开发的角度来说也是尽量避免select * 此类写法（我目前使用的方案）。
2. 根据select * 出来的表信息从对应的元数据获取表结构。例：如果是mysql表，则使用表名从mysql的information_schema.COLUMNS表获取列信息。
